/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;
import Conexion.ConexionBD;
/**
 *
 * @author Lenovo
 */
public class FrmMaterias extends javax.swing.JFrame {

    /**
     * Creates new form FrmMaterias
     */
    public FrmMaterias() {
        initComponents();
        listarMaterias();
        cargarComboBoxMaestros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreMateria = new javax.swing.JTextField();
        txtCreditos = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));

        jLabel1.setText("Nombre de materia");

        jLabel2.setText("Creditos");

        jLabel3.setText("Maestro");

        txtNombreMateria.setName("txtNombreMateria"); // NOI18N
        txtNombreMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreMateriaActionPerformed(evt);
            }
        });

        txtCreditos.setName("txtCreditos"); // NOI18N
        txtCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreditosActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setName("cboMaestro"); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(51, 51, 255));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardarrrr(1).png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setName("btnGuardar"); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(255, 0, 0));
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.setName("btnEditar"); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setName("btnEliminar"); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(0, 51, 255));
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setName("btnLimpiar"); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Materia", "Creditos", "Maestro"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salirrr.jpg"))); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("CONSULTA DE MATERIAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCreditos, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNombreMateria, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );

        txtNombreMateria.getAccessibleContext().setAccessibleName("");
        btnEditar.getAccessibleContext().setAccessibleDescription("Editar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txtNombreMateria.getText().trim().isEmpty() || txtCreditos.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Validar que se haya seleccionado un maestro real de la lista
    String maestroSeleccionado = jComboBox1.getSelectedItem().toString();
    if (maestroSeleccionado.equals("Selecciona un maestro...")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, asigna un maestro a la materia.", "Error", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        // 2. Validación de formato de números
        int creditos = Integer.parseInt(txtCreditos.getText().trim());

        // 3. Consulta SQL incluyendo la columna id_maestro que tiene tu tabla materias
        String sql = "INSERT INTO materias (nombre_materia, creditos, id_maestro) VALUES (?, ?, ?)";
        
        java.sql.Connection con = Conexion.ConexionBD.getConexion();
        java.sql.PreparedStatement ps = con.prepareStatement(sql);
        
        ps.setString(1, txtNombreMateria.getText().trim());
        ps.setInt(2, creditos);
        
        // Buscamos el ID del maestro seleccionado (por ejemplo, "Juan Pérez" -> retorna 1)
        int idMaestro = obtenerIdProfesor(maestroSeleccionado);
        ps.setInt(3, idMaestro);
        
        // 4. EJECUTAR LA INSERCIÓN CORRECTAMENTE 
        int resultado = ps.executeUpdate(); // ⬅️ IMPORTANTE: Cambiado a executeUpdate() estándar
        
        if (resultado > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Materia registrada con éxito en la base de datos.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            // Limpiamos los cuadros de texto
            txtNombreMateria.setText("");
            txtCreditos.setText("");
            jComboBox1.setSelectedIndex(0); 
            
            // Recargamos la tabla de la derecha automáticamente
            listarMaterias(); 
        }
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "El campo Créditos debe ser un número entero válido.", "Error", javax.swing.JOptionPane.WARNING_MESSAGE);
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error en la base de datos: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        if (txtNombreMateria.getText().trim().isEmpty() || txtCreditos.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios para editar.", "Error", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    try {
        int creditos = Integer.parseInt(txtCreditos.getText().trim());
        String nombre = txtNombreMateria.getText().trim();
        
        // Modifica los créditos basándose en el nombre de la materia
        String sql = "UPDATE materias SET creditos = ? WHERE nombre_materia = ?";
        java.sql.Connection con = Conexion.ConexionBD.getConexion();
        java.sql.PreparedStatement ps = con.prepareStatement(sql);
        ps.setInt(1, creditos);
        ps.setString(2, nombre);
        
        int resultado = ps.executeUpdate();
        if (resultado > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Materia actualizada correctamente.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            listarMaterias(); // Actualiza la tabla
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró la materia para modificar.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Créditos debe ser un número válido.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al editar: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
      }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
        String nombre = txtNombreMateria.getText().trim();
    if (nombre.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Escribe el nombre de la materia que deseas eliminar.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Cuadro de diálogo de confirmación (Requisito)
    int confirmar = javax.swing.JOptionPane.showConfirmDialog(this, "¿De verdad deseas eliminar la materia " + nombre + "?", "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
        try {
            String sql = "DELETE FROM materias WHERE nombre_materia = ?";
            java.sql.Connection con = Conexion.ConexionBD.getConexion();
            java.sql.PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, nombre);
            
            int resultado = ps.executeUpdate();
            if (resultado > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Materia eliminada con éxito.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                txtNombreMateria.setText("");
                txtCreditos.setText("");
                listarMaterias(); // Esto actualizará la tabla automáticamente
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No se encontró esa materia.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (java.sql.SQLException e) {
            if (e.getErrorCode() == 1451) { // 1451 es el código de error de MySQL para llaves foráneas
        javax.swing.JOptionPane.showMessageDialog(this, 
            "No se puede eliminar esta materia porque tiene calificaciones o alumnos asignados.", 
            "Acción Denegada", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtNombreMateria.setText("");
        txtCreditos.setText("");
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtNombreMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMateriaActionPerformed

    private void txtCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreditosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreditosActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMaterias().setVisible(true);
            }
        });
    }
    public void listarMaterias() {
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
    modelo.addColumn("ID");
    modelo.addColumn("Materia");
    modelo.addColumn("Créditos");
    modelo.addColumn("Maestro"); 
    
    jTable1.setModel(modelo);
    
    // Consulta 100% revisada con tu Workbench: p.nombre y p.apellido_paterno
    String sql = "SELECT m.id_materia, m.nombre_materia, m.creditos, CONCAT(p.nombre, ' ', p.apellido_paterno) AS maestro " +
                 "FROM materias m " +
                 "LEFT JOIN maestros p ON m.id_maestro = p.id_maestro";
                 
    try {
        java.sql.Connection con = Conexion.ConexionBD.getConexion();
        java.sql.PreparedStatement ps = con.prepareStatement(sql);
        java.sql.ResultSet rs = ps.executeQuery();
        
        while (rs.next()) {
            Object[] fila = new Object[4];
            fila[0] = rs.getInt("id_materia");
            fila[1] = rs.getString("nombre_materia");
            fila[2] = rs.getInt("creditos");
            fila[3] = rs.getString("maestro") != null ? rs.getString("maestro") : "Sin asignar";
            modelo.addRow(fila);
        }
    } catch (java.sql.SQLException e) {
        System.out.println("Error al llenar la tabla: " + e.getMessage());
    }
}
    public void cargarComboBoxMaestros() {
    jComboBox1.removeAllItems(); 
    jComboBox1.addItem("Selecciona un maestro...");
    
    // Consulta limpia usando las columnas exactas de tu imagen de Workbench
    String sql = "SELECT nombre, apellido_paterno FROM maestros"; 
    try {
        java.sql.Connection con = Conexion.ConexionBD.getConexion();
        java.sql.PreparedStatement ps = con.prepareStatement(sql);
        java.sql.ResultSet rs = ps.executeQuery();
        
        while (rs.next()) {
            String nombreCompleto = rs.getString("nombre") + " " + rs.getString("apellido_paterno");
            jComboBox1.addItem(nombreCompleto);
        }
    } catch (java.sql.SQLException e) {
        System.out.println("Error al cargar maestros: " + e.getMessage());
    }
}
    public int obtenerIdProfesor(String nombreCompleto) {
    int id = 0;
    String sql = "SELECT id_maestro FROM maestros WHERE CONCAT(nombre, ' ', apellido_paterno) = ?";
    try {
        java.sql.Connection con = Conexion.ConexionBD.getConexion();
        java.sql.PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, nombreCompleto);
        java.sql.ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            id = rs.getInt("id_maestro");
        }
    } catch (java.sql.SQLException e) {
        System.out.println("Error al obtener ID del maestro: " + e.getMessage());
    }
    return id;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCreditos;
    private javax.swing.JTextField txtNombreMateria;
    // End of variables declaration//GEN-END:variables
}
