/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import Conexion.ConexionBD;
/**
 *
 * @author Lenovo
 */
public class FrmReporte extends javax.swing.JFrame {

    /**
     * Creates new form FrmReporte
     */
    public FrmReporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbReportes = new javax.swing.JComboBox<>();
        btnGenerar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SELECCIONE EL TIPO DE REPORTE");

        cmbReportes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Listado General de Alumnos", "Listado de Maestros", "Listado de Materias", "Calificaciones por Alumno", "Reporte de Carreras" }));

        btnGenerar.setBackground(new java.awt.Color(51, 51, 255));
        btnGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerar.setText("Generar PDF");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(255, 0, 0));
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGenerar)
                        .addGap(39, 39, 39)
                        .addComponent(btnRegresar))
                    .addComponent(cmbReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(394, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(cmbReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerar)
                    .addComponent(btnRegresar))
                .addContainerGap(412, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
String seleccion = cmbReportes.getSelectedItem().toString(); 
    
    // 2. Abrir el selector de archivos
    javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    int respuesta = fileChooser.showSaveDialog(this);

    if (respuesta == javax.swing.JFileChooser.APPROVE_OPTION) {
        String ruta = fileChooser.getSelectedFile().getAbsolutePath();
        if (!ruta.endsWith(".pdf")) {
            ruta += ".pdf";
        }

        // 3. LLAMAR AL MÉTODO PASANDO AMBOS DATOS: LA RUTA Y LA SELECCIÓN
        generarPDF(ruta, seleccion);
    }
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
         this.dispose();
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmReporte().setVisible(true);
            }
        });
    }
    
    public void generarPDF(String ruta, String tipoReporte) {
    try {
        com.itextpdf.text.Document documento = new com.itextpdf.text.Document();
        com.itextpdf.text.pdf.PdfWriter.getInstance(documento, new java.io.FileOutputStream(ruta));
        documento.open();

        documento.add(new com.itextpdf.text.Paragraph("REPORTE: " + tipoReporte));
        documento.add(new com.itextpdf.text.Paragraph("Fecha: " + java.time.LocalDate.now()));
        documento.add(new com.itextpdf.text.Paragraph("--------------------------------------------------"));

        java.sql.Connection cn = Conexion.ConexionBD.getConexion();
        java.sql.Statement st = cn.createStatement();
        java.sql.ResultSet rs = null;

        // Selección de consulta basada en el texto del JComboBox
        if (tipoReporte.equals("Listado General de Alumnos")) {
            rs = st.executeQuery("SELECT matricula, nombre FROM alumnos");
            while (rs.next()) {
                documento.add(new com.itextpdf.text.Paragraph("Matrícula: " + rs.getString("matricula") + " - Nombre: " + rs.getString("nombre")));
            }
        } else if (tipoReporte.equals("Listado de Maestros")) {
            rs = st.executeQuery("SELECT id_maestro, nombre FROM maestros");
            while (rs.next()) {
                documento.add(new com.itextpdf.text.Paragraph("ID: " + rs.getString("id_maestro") + " - Nombre: " + rs.getString("nombre")));
            }
        } else if (tipoReporte.equals("Listado de Materias")) {
            rs = st.executeQuery("SELECT id_materia, nombre_materia FROM materias");
            while (rs.next()) {
                documento.add(new com.itextpdf.text.Paragraph("ID: " + rs.getString("id_materia") + " - Materia: " + rs.getString("nombre_materia")));
            }
        } else if (tipoReporte.equals("Calificaciones por Alumno")) {
            // Cambiamos el SELECT para traer la columna 'calificacion'
            rs = st.executeQuery("SELECT id_alumno, calificacion FROM calificaciones");
            while (rs.next()) {
                // Mostramos el ID del alumno y su calificación/promedio
                documento.add(new com.itextpdf.text.Paragraph("ID Alumno: " + rs.getString("id_alumno") + 
                                                              " | Calificación: " + rs.getString("calificacion")));
            }
        } else if (tipoReporte.equals("Reporte de Carreras")) {
            rs = st.executeQuery("SELECT id_carrera, nombre_carrera FROM carrera");
            while (rs.next()) {
                documento.add(new com.itextpdf.text.Paragraph("ID: " + rs.getString("id_carrera") + " - Carrera: " + rs.getString("nombre_carrera")));
            }
        }

        documento.close();
        cn.close();
        javax.swing.JOptionPane.showMessageDialog(this, "PDF generado con éxito.");

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    }
}
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbReportes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
